// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbIewr2drdgxQjPFFErJWZL9ACl7r6huY',
    appId: '1:679808593250:web:901f8cf00827560474503b',
    messagingSenderId: '679808593250',
    projectId: 'chatappassignment-134f6',
    authDomain: 'chatappassignment-134f6.firebaseapp.com',
    storageBucket: 'chatappassignment-134f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLKsz9IMNPOqdkkbU_kJ1DRvNP2It-mwY',
    appId: '1:679808593250:android:d1bd2a87e073fc0a74503b',
    messagingSenderId: '679808593250',
    projectId: 'chatappassignment-134f6',
    storageBucket: 'chatappassignment-134f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQQmx6dcQQMq3DDWnmuH1mR1_plHNzHk',
    appId: '1:679808593250:ios:6a9e5385d576245574503b',
    messagingSenderId: '679808593250',
    projectId: 'chatappassignment-134f6',
    storageBucket: 'chatappassignment-134f6.appspot.com',
    iosBundleId: 'com.example.flutterchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQQmx6dcQQMq3DDWnmuH1mR1_plHNzHk',
    appId: '1:679808593250:ios:6a9e5385d576245574503b',
    messagingSenderId: '679808593250',
    projectId: 'chatappassignment-134f6',
    storageBucket: 'chatappassignment-134f6.appspot.com',
    iosBundleId: 'com.example.flutterchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbIewr2drdgxQjPFFErJWZL9ACl7r6huY',
    appId: '1:679808593250:web:d10f231b6115041a74503b',
    messagingSenderId: '679808593250',
    projectId: 'chatappassignment-134f6',
    authDomain: 'chatappassignment-134f6.firebaseapp.com',
    storageBucket: 'chatappassignment-134f6.appspot.com',
  );
}